### PR TITLE
Pbw 5964

### PR DESCRIPTION
**Pull request by nagavenivn**

### CODE REVIEW

**Comment by pilievOoyala** [comment]
Shouldn't this code be in the logic for replaying.  What if I call replay before the video ends?

**Comment by nagavenivn** [comment]
@pilievOoyala: This fix is when initial time is set to more than the video duration. So video will end as soon as you start playing it.

**Comment by pilievOoyala** [comment]
I agree that this generates the error immediately. But we should do the initialtime =0 reseting in the replay logic.  In case we need to preserve the number for something in the skin.  Also, maybe add in some logic to change initialTime to the length of the video(if it's greater), when we know the length of the video. (It could also fix negative initial times).

**Comment by nagavenivn** [comment]
As per current implementation, if this value is not reset till replay then TIME_UPDATE event is not  sent at all which will affect skin. Also I don't think this value is needed later for skin. 

Tested for negative value and found this.setInitialTime() is called with time set to zero when it is negative. So we should not be worrying for this.

I believe all above is as per design and requirement and we should not change anything to fix the problem mentioned for this ticket.

**Comment by pilievOoyala** [comment]
Looks good.

**Pull request merged**
