### PR TITLE
[PBF-556-master]Selected bitrate is not retaining on replay

### PR DESCRIPTION
**Pull request by sarita-ooyala**

### CODE REVIEW

**Comment by angieisrani** [comment]
There is some logic in this code that checks if the resource is null and only acts when it is null such as loading a new stream.  Will that sitll work with this chagne?  For example if you set a new url with the same element, will the value get set properly?
In particular I"m looking at the loadMediaSource function

**Comment by sarita-ooyala** [comment]
Hi Angie,


Cause of the issue - Parameter preload = true by default in FF and Safari
                                 Parameter preload = false by default in
chrome, this is done in core.js. Following is the line of code for this -

 Code block -

// Determine whether or not to preload based on platform
// TODO (neeraj): do we only need to default false on specific versions?
    var canPreload = !(OO.isChrome || OO.isIos || OO.isAndroid);


Proposed solution - Resource is set to null only in destroy and not when
playback completes. This is done because, since in FF and safari preload =
true, a new resource is created on replay and the last selected bitrate for
the video cannot be retained. Where as, in chrome preload = false and hence
the existing resource is used on replay , there by retains the last
selected bitrate.

When a video is selected from discovery tray, a new resource is created and
hence the code works fine.

Also, the code for setting resource = null in onPlayComplete was added as
the part of the solution for PBF-477 (Playhead time returning junk value on
replay). But, this was not the actual solution for that issue. So, removing
this line of code does not effect any other functionality.


Thanks
Sarita Singh

On Mon, Apr 18, 2016 at 5:26 PM, angieisrani <notifications@github.com>
wrote:

> There is some logic in this code that checks if the resource is null and
> only acts when it is null such as loading a new stream. Will that sitll
> work with this chagne? For example if you set a new url with the same
> element, will the value get set properly?
> In particular I"m looking at the loadMediaSource function
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ooyala/html5-video-plugins/pull/148#issuecomment-211648434>
>



-- 
Best Regards,
Sarita Singh

**Comment by angieisrani** [comment]
@sarita-ooyala I understand, but can you take a look at the loadMediaSource api which only takes action if the url is null?  Is this going to continue to work?
Note that you can somewhat test preloading by overriding the value as needed, except of course you will be limited by the canPreload check noted above

**Comment by angieisrani** [comment]
Looks good to me - would you mind reresolving with master?

**Comment by sarita-ooyala** [comment]
Resolved merge conflicts

**Comment by angieisrani** [comment]
LGTM

**Pull request merged**
