### PR TITLE
[PBW-5865] Update unit test

### PR DESCRIPTION
**Pull request by mityaha**

### CODE REVIEW

**Comment by aeng7** [comment]
Can we include a test for Edge as well?

**Comment by aeng7** [comment]
Otherwise looks good to me!

**Comment by mityaha** [comment]
I was thinking about adding Edge, but then decided not to, as it will be 99.9% duplicate code.  We don't always repeat the exactly the same tests for each of the browsers, but OK, will do.

**Comment by mityaha** [comment]
Done

**Comment by aeng7** [comment]
LGTM

**Pull request merged**
