### PR TITLE
[PBW-4409] Manually raise TIME_UPDATE event on seek from pause to address Firefox

### PR DESCRIPTION
**Pull request by brianfwong**
Despite comments about the commit. Moving this to a pull request so it can be better tracked if it needs to be edited or if it is found to be mergable.

See comment history in the commit before making any decision to merge this.

### CODE REVIEW

**Comment by aldigun** [comment]
So it is underlying browser thing that does not publish the expected event. Have you test with other browser? chrome, IE, iOS and Android?

**Comment by SainiBasu** [comment]
@aldigun Yes this is a browser dependent issue. The TIME_UPDATE event gets triggered automatically after SEEKED in Chrome. But in FF and Safari, it doesn't happen on its own and needs a user interruption to trigger the TIME_UPDATE. One thing that needs to be noted is that the playhead time gets updated after SEEKED, just that the TIME_UPDATE has to be called with the updated playhead time.

**Comment by aldigun** [comment]
Have you tested this with other browser, are they working well?
Have you tested this with ads?

**Comment by SainiBasu** [comment]
The issue was found with FF and Safari. We tested a video which had pre, mid and postroll ads - When seeked somewhere in between, the midroll ad played and then the video continued. When seeked till the end, the postroll played and then the endscreen showed up. Seeking the video back and forth also worked fine with our fix. Link used  - [link](http://debug.ooyala.com/ea/index.html?ec=NscGg4bzpO9s5rUMyW-AAfoeEA7CX6hP&pbid=ab3bfc9b98714e088fa39bc6666dc8e3&pcode=NuOXQxOiwRc-kxosTLeJjoQ74W_D&core_player=https%3A%2F%2Fplayer.ooyala.com%2Fstatic%2Fv4%2Fcandidate%2Flatest%2Fcore.min.js&video_plugins=http%3A%2F%2Flocalhost%3A8000%2Fhtml5-video-plugins%2Fbuild%2Fmain_html5.min.js&html5_skin=http%3A%2F%2Fplayer.ooyala.com%2Fstatic%2Fv4%2Fcandidate%2Flatest%2Fskin-plugin%2Fhtml5-skin.js&skin_asset=http%3A%2F%2Fplayer.ooyala.com%2Fstatic%2Fv4%2Fcandidate%2Flatest%2Fskin-plugin%2Fhtml5-skin.css&skin_config=http%3A%2F%2Fplayer.ooyala.com%2Fstatic%2Fv4%2Fcandidate%2Flatest%2Fskin-plugin%2Fskin.json&ad_plugin=http%3A%2F%2Fplayer.ooyala.com%2Fstatic%2Fv4%2Fcandidate%2Flatest%2Fad-plugin%2Ffreewheel.min.js&options=%7B%22freewheel-ads-manager%22%3A%7B%22fw_video_asset_id%22%3A%22NscGg4bzpO9s5rUMyW-AAfoeEA7CX6hP%22%2C%22html5_ad_server%22%3A%22http%3A%2F%2Fg1.v.fwmrm.net%22%2C%22fw_android_ad_server%22%3A%22http%3A%2F%2Fg1.v.fwmrm.net%2F%22%2C%22html5_player_profile%22%3A%2290750%3Aooyala_html5%22%2C%22fw_android_player_profile%22%3A%2290750%3Aooyala_android%22%2C%22fw_mrm_network_id%22%3A%22380912%22%7D%2C%22loop%22%3Atrue%7D)

**Comment by brianfwong** [comment]
Mac tests (windows pending):
Mac Chrome: Pass
Mac Chrome with Ads: Pass
Mac Safari: pass
Mac Safari with Ads: Pass
Mac Firefox: pass
Mac Firefox with Ads: FAIL

In Mac Firefox with Ads, doing pp.seek(20) during the preroll let me SKIP the ad. Doing it during the midroll ALSO lets me SKIP the ad.
- Rechecking to be sure this difference IS this bug, or something else (I thought I recalled a different bug were you could seek out of ads, but haven't been able to find it). Merged master into this codebase to be sure this was not some other bug that had been solved after PBW-4409's code had been checked in. Issue still there.

**Comment by brianfwong** [comment]
I can seek out of ads, even when not using this code. That issue is not 'caused' by this fix, but is not solved by it either.

The original test link, without this code, seek actually does move the video, but the scrubber bar and pp.getPlayheadTime() fail to update.

**Pull request merged**
